{
  "openapi" : "3.0.1",
  "info" : {
    "title" : "SASE IA - Resource API",
    "version" : "v3"
  },
  "servers" : [ {
    "url" : "http://localhost:8080"
  }, {
    "url" : "https://dev.api.sase.paloaltonetworks.com"
  }, {
    "url" : "https://qa.api.sase.paloaltonetworks.com"
  }, {
    "url" : "https://staging.us.api.sase.paloaltonetworks.com"
  }, {
    "url" : "https://api.sase.paloaltonetworks.com"
  } ],
  "security" : [ {
    "JWT" : [ ]
  } ],
  "paths" : {
    "/insights/v3.0/resource/query/locations/location_current_status_count" : {
      "post" : {
        "summary" : "Endpoint to get count of location current status.",
        "operationId" : "getLocationCurrentStatusCount",
        "requestBody" : {
          "content" : {
            "application/json" : {
              "schema" : {
                "required" : [ ],
                "type" : "object",
                "properties" : {
                  "event_time" : {
                    "type" : "string",
                    "description" : "Time of the event",
                    "example" : "1709226000000"
                  },
                  "edge_location_display_name" : {
                    "type" : "string",
                    "description" : "Name of PA location",
                    "example" : "US West"
                  },
                  "mu_state" : {
                    "type" : "INTEGER",
                    "description" : "State of the MU",
                    "example" : 1,
                    "enum" : [ 0, 1, 2, 3 ]
                  },
                  "rn_state" : {
                    "type" : "INTEGER",
                    "description" : "State of the RN",
                    "example" : 1,
                    "enum" : [ 0, 1, 2, 3 ]
                  },
                  "sc_state" : {
                    "type" : "INTEGER",
                    "description" : "State of the SC",
                    "example" : 1,
                    "enum" : [ 0, 1, 2 ]
                  },
                  "ep_state" : {
                    "type" : "INTEGER",
                    "description" : "State of the EP",
                    "example" : 1,
                    "enum" : [ 0, 1, 2 ]
                  },
                  "nhp_state" : {
                    "type" : "INTEGER",
                    "description" : "State of the NHP",
                    "example" : 1,
                    "enum" : [ 0, 1, 2 ]
                  }
                }
              },
              "examples" : {
                "Remote Networks - with adem filter" : {
                  "value" : {
                    "filter" : {
                      "rules" : [ {
                        "property" : "event_time",
                        "operator" : "last_n_hours",
                        "values" : [ 5 ]
                      }, {
                        "property" : "rn_state",
                        "operator" : "in",
                        "values" : [ 1 ]
                      } ]
                    },
                    "properties" : [ {
                      "property" : "rn_state"
                    }, {
                      "property" : "current_rn_location"
                    } ]
                  }
                },
                "Monitor > Prisma Access Locations > Prisma Access Location Status" : {
                  "value" : {
                    "filter" : {
                      "rules" : [ {
                        "property" : "rn_state",
                        "operator" : "in",
                        "values" : [ 1 ]
                      } ]
                    },
                    "properties" : [ {
                      "property" : "rn_state"
                    }, {
                      "property" : "current_rn_location"
                    } ]
                  }
                }
              }
            }
          },
          "required" : true
        },
        "responses" : {
          "200" : {
            "description" : "OK",
            "content" : {
              "application/json" : {
                "schema" : {
                  "type" : "object",
                  "properties" : {
                    "current_mu_locations" : {
                      "type" : "integer",
                      "description" : "Count of the mobile-user locations"
                    },
                    "current_rn_locations" : {
                      "type" : "integer",
                      "description" : "Count of the remote-network locations"
                    },
                    "current_sc_locations" : {
                      "type" : "integer",
                      "description" : "Count of the service-connection locations"
                    },
                    "current_ep_locations" : {
                      "type" : "integer",
                      "description" : "Count of the explicit-proxy locations"
                    },
                    "current_nhp_locations" : {
                      "type" : "integer",
                      "description" : "Count of next hop proxy locations"
                    }
                  }
                }
              }
            }
          }
        }
      },
      "parameters" : [ {
        "name" : "Prisma-Tenant",
        "in" : "header",
        "description" : "TSG ID",
        "required" : false,
        "schema" : {
          "type" : "string"
        }
      } ]
    },
    "/insights/v3.0/resource/query/locations/noc_location_list_rn_sc_status" : {
      "post" : {
        "summary" : "Prisma Access Locations with SC and RNs along with its coordinates and counts of RN and SC",
        "operationId" : "getNocLocationListRNSC",
        "requestBody" : {
          "content" : {
            "application/json" : {
              "schema" : {
                "required" : [ ],
                "type" : "object",
                "properties" : {
                  "edge_location_display_name" : {
                    "type" : "string",
                    "description" : "Name of PA location",
                    "example" : "US West"
                  },
                  "source_country" : {
                    "type" : "string",
                    "description" : "Name of country",
                    "example" : "United States"
                  },
                  "source_city" : {
                    "type" : "string",
                    "description" : "Name of city",
                    "example" : "Santa Clara"
                  }
                }
              },
              "example" : {
                "filter" : {
                  "rules" : [ {
                    "property" : "edge_location_display_name",
                    "operator" : "in",
                    "values" : [ "US West" ]
                  }, {
                    "property" : "source_country",
                    "operator" : "in",
                    "values" : [ "United States" ]
                  }, {
                    "property" : "source_city",
                    "operator" : "in",
                    "values" : [ "Santa Clara" ]
                  } ]
                }
              }
            }
          },
          "required" : true
        },
        "responses" : {
          "200" : {
            "description" : "OK",
            "content" : {
              "application/json" : {
                "schema" : {
                  "type" : "object",
                  "properties" : {
                    "edge_location_display_name" : {
                      "type" : "string",
                      "description" : "Name of PA location"
                    },
                    "latitude" : {
                      "type" : "number",
                      "description" : "Latitude for the PA Location"
                    },
                    "longitude" : {
                      "type" : "number",
                      "description" : "Longitude for the PA Location"
                    },
                    "aggregate_status" : {
                      "type" : "string",
                      "description" : "Status of the PA Location - UP/DOWN"
                    },
                    "sc_status" : {
                      "type" : "string",
                      "description" : "Service Connection Status of the PA Location - UP/DOWN"
                    },
                    "sc_up_count" : {
                      "type" : "integer",
                      "description" : "Number of SC sites which are up"
                    },
                    "rn_status" : {
                      "type" : "string",
                      "description" : "RN Status of the PA Location - UP/DOWN"
                    },
                    "rn_up_count" : {
                      "type" : "integer",
                      "description" : "Number of RN sites which are up"
                    }
                  }
                }
              }
            }
          }
        }
      },
      "parameters" : [ {
        "name" : "Prisma-Tenant",
        "in" : "header",
        "description" : "TSG ID",
        "required" : false,
        "schema" : {
          "type" : "string"
        }
      } ]
    },
    "/insights/v3.0/resource/query/locations/location_gp_mobile_users_logins" : {
      "post" : {
        "summary" : "Endpoint to get list of all PA Location with SC and RNs along with its coordinates and counts of RN and SC",
        "operationId" : "getLocationGPMobileUsersLogins",
        "requestBody" : {
          "content" : {
            "application/json" : {
              "schema" : {
                "required" : [ "event_time" ],
                "type" : "object",
                "properties" : {
                  "event_time" : {
                    "type" : "string",
                    "description" : "Time of the event",
                    "example" : "1709226000000"
                  },
                  "edge_location_display_name" : {
                    "type" : "string",
                    "description" : "Name of PA location",
                    "example" : "US West"
                  },
                  "node_type" : {
                    "type" : "number",
                    "description" : "Type of the node",
                    "example" : 48
                  }
                }
              },
              "example" : {
                "filter" : {
                  "rules" : [ {
                    "property" : "event_time",
                    "operator" : "last_n_hours",
                    "values" : [ 5 ]
                  }, {
                    "property" : "edge_location_display_name",
                    "operator" : "in",
                    "values" : [ "US West" ]
                  }, {
                    "property" : "node_type",
                    "operator" : "in",
                    "values" : [ 48 ]
                  } ]
                }
              }
            }
          },
          "required" : true
        },
        "responses" : {
          "200" : {
            "description" : "OK",
            "content" : {
              "application/json" : {
                "schema" : {
                  "type" : "object",
                  "properties" : {
                    "edge_location_display_name" : {
                      "type" : "string",
                      "description" : "Display name of the location"
                    },
                    "unique_users" : {
                      "type" : "integer",
                      "description" : "Number of unique GlobalProtect users at the location"
                    },
                    "unique_users_gp" : {
                      "type" : "integer",
                      "description" : "Number of unique GlobalProtect users at the location"
                    }
                  }
                }
              }
            }
          }
        }
      },
      "parameters" : [ {
        "name" : "Prisma-Tenant",
        "in" : "header",
        "description" : "TSG ID",
        "required" : false,
        "schema" : {
          "type" : "string"
        }
      } ]
    },
    "/insights/v3.0/resource/query/locations/noc_location_list_timeseries" : {
      "post" : {
        "summary" : "Endpoint to get list of all PA Location along with its coordinates and information about sites and mobileusers",
        "operationId" : "getNocLocationList",
        "requestBody" : {
          "content" : {
            "application/json" : {
              "schema" : {
                "required" : [ ],
                "type" : "object",
                "properties" : {
                  "edge_location_display_name" : {
                    "type" : "string",
                    "description" : "Name of PA location",
                    "example" : "US West"
                  },
                  "source_country" : {
                    "type" : "string",
                    "description" : "Name of country",
                    "example" : "United States"
                  },
                  "source_city" : {
                    "type" : "string",
                    "description" : "Name of city",
                    "example" : "Santa Clara"
                  }
                }
              },
              "example" : {
                "filter" : {
                  "rules" : [ {
                    "property" : "edge_location_display_name",
                    "operator" : "in",
                    "values" : [ "US West" ]
                  }, {
                    "property" : "source_country",
                    "operator" : "in",
                    "values" : [ "United States" ]
                  }, {
                    "property" : "source_city",
                    "operator" : "in",
                    "values" : [ "Santa Clara" ]
                  } ]
                }
              }
            }
          },
          "required" : true
        },
        "responses" : {
          "200" : {
            "description" : "OK",
            "content" : {
              "application/json" : {
                "schema" : {
                  "type" : "object",
                  "properties" : {
                    "edge_location_display_name" : {
                      "type" : "string",
                      "description" : "Name of PA location"
                    },
                    "latitude" : {
                      "type" : "number",
                      "description" : "Latitude for the PA Location"
                    },
                    "longitude" : {
                      "type" : "number",
                      "description" : "Longitude for the PA Location"
                    },
                    "aggregate_status" : {
                      "type" : "string",
                      "description" : "Status of the PA Location - UP/DOWN"
                    },
                    "mu_status" : {
                      "type" : "string",
                      "description" : "Mobile gateway Status of the PA Location - UP/DOWN"
                    },
                    "sc_status" : {
                      "type" : "string",
                      "description" : "Service Connection Status of the PA Location - UP/DOWN"
                    },
                    "sc_up_count" : {
                      "type" : "integer",
                      "description" : "Number of SC sites which are up"
                    },
                    "connected_user_count" : {
                      "type" : "integer",
                      "description" : "Number of GP mobileusers connected to PA Location"
                    }
                  }
                }
              }
            }
          }
        }
      },
      "parameters" : [ {
        "name" : "Prisma-Tenant",
        "in" : "header",
        "description" : "TSG ID",
        "required" : false,
        "schema" : {
          "type" : "string"
        }
      } ]
    },
    "/insights/v3.0/resource/query/locations/location_list_timeseries_gp_mobileusers" : {
      "post" : {
        "summary" : "Endpoint to get list all pa locations with current connected gp users",
        "operationId" : "getLocationsGpUserCount",
        "requestBody" : {
          "content" : {
            "application/json" : {
              "schema" : {
                "required" : [ ],
                "type" : "object",
                "properties" : {
                  "event_time" : {
                    "type" : "string",
                    "description" : "Time of the event",
                    "example" : "1709226000000"
                  },
                  "edge_location_display_name" : {
                    "type" : "string",
                    "description" : "Name of PA location",
                    "example" : "US West"
                  }
                }
              },
              "example" : {
                "filter" : {
                  "rules" : [ {
                    "property" : "event_time",
                    "operator" : "last_n_hours",
                    "values" : [ 5 ]
                  }, {
                    "property" : "edge_location_display_name",
                    "operator" : "in",
                    "values" : [ "US West" ]
                  } ]
                }
              }
            }
          },
          "required" : true
        },
        "responses" : {
          "200" : {
            "description" : "OK",
            "content" : {
              "application/json" : {
                "schema" : {
                  "type" : "object",
                  "properties" : {
                    "edge_location_display_name" : {
                      "type" : "string",
                      "description" : "Display name of the location"
                    },
                    "unique_users_gp" : {
                      "type" : "integer",
                      "description" : "Number of unique GlobalProtect users at the location"
                    }
                  }
                }
              }
            }
          }
        }
      },
      "parameters" : [ {
        "name" : "Prisma-Tenant",
        "in" : "header",
        "description" : "TSG ID",
        "required" : false,
        "schema" : {
          "type" : "string"
        }
      } ]
    }
  },
  "components" : {
    "securitySchemes" : {
      "JWT" : {
        "type" : "http",
        "description" : "JWT authentication with bearer token",
        "scheme" : "bearer",
        "bearerFormat" : "Bearer [token]"
      }
    }
  }
}