{
  "openapi" : "3.0.1",
  "info" : {
    "title" : "SASE IA - Resource API",
    "version" : "v3"
  },
  "servers" : [ {
    "url" : "http://localhost:8080"
  }, {
    "url" : "https://dev.api.sase.paloaltonetworks.com"
  }, {
    "url" : "https://qa.api.sase.paloaltonetworks.com"
  }, {
    "url" : "https://staging.us.api.sase.paloaltonetworks.com"
  }, {
    "url" : "https://api.sase.paloaltonetworks.com"
  } ],
  "security" : [ {
    "JWT" : [ ]
  } ],
  "paths" : {
    "/insights/v3.0/resource/query/sites/bandwidth_consumption_histogram" : {
      "post" : {
        "summary" : "Bandwidth consumption over time, calculating average, peak, and median values for ingress and egress traffic",
        "operationId" : "getBandwidthConsumptionHistogram",
        "tags": "Bandwidth consumption histogram",
        "requestBody" : {
          "content" : {
            "application/json" : {
              "schema" : {
                "required" : [ "event_time" ],
                "type" : "object",
                "properties" : {
                  "event_time" : {
                    "type" : "string",
                    "description" : "Time of the event",
                    "example" : "1709226000000"
                  },
                  "site_state" : {
                    "type" : "number",
                    "description" : "State of the site",
                    "example" : 0
                  },
                  "edge_location_display_name" : {
                    "type" : "string",
                    "description" : "Name of PA location",
                    "example" : "US West"
                  },
                  "site_name" : {
                    "type" : "string",
                    "description" : "Name of the site",
                    "example" : "Remote-Conn1"
                  },
                  "node_type" : {
                    "type" : "number",
                    "description" : "Type of the node",
                    "example" : 48
                  },
                  "instance_state" : {
                    "type" : "number",
                    "description" : "Instance state",
                    "example" : 1
                  },
                  "compute_location" : {
                    "type" : "string",
                    "description" : "Location of the compute",
                    "example" : "US East"
                  }
                }
              },
              "examples" : {
                "Bandwidth consumption histogram" : {
                  "value" : {
                    "filter" : {
                      "rules" : [ {
                        "property" : "event_time",
                        "operator" : "last_n_hours",
                        "values" : [ 5 ]
                      }, {
                        "property" : "node_type",
                        "operator" : "in",
                        "values" : [ 48 ]
                      } ]
                    },
                    "histogram" : {
                      "property" : "event_time",
                      "range" : "minute",
                      "enableEmptyInterval" : true,
                      "value" : 30
                    }
                  }
                }
              }
            }
          },
          "required" : true
        },
        "responses" : {
          "200" : {
            "description" : "OK",
            "content" : {
              "application/json" : {
                "schema" : {
                  "type" : "object",
                  "properties" : {
                    "event_time" : {
                      "type" : "string",
                      "description" : "event time"
                    },
                    "avg_ingress" : {
                      "type" : "number",
                      "description" : "Average Ingress Bandwidth consumed"
                    },
                    "avg_egress" : {
                      "type" : "number",
                      "description" : "Average Egress Bandwidth consumed"
                    },
                    "peak_ingress" : {
                      "type" : "number",
                      "description" : "Peak Ingress Bandwidth consumed"
                    },
                    "peak_egress" : {
                      "type" : "number",
                      "description" : "Peak Egress Bandwidth consumed"
                    },
                    "median_ingress" : {
                      "type" : "number",
                      "description" : "Median Ingress Bandwidth consumed"
                    },
                    "median_egress" : {
                      "type" : "number",
                      "description" : "Median Egress Bandwidth consumed"
                    }
                  }
                }
              }
            }
          }
        }
      },
      "parameters" : [ {
        "name" : "Prisma-Tenant",
        "in" : "header",
        "description" : "TSG ID",
        "required" : false,
        "schema" : {
          "type" : "string"
        }
      } ]
    },
    "/insights/v3.0/resource/query/sites/rn_list" : {
      "post" : {
        "summary" : "Endpoint to get list of all RNs.",
        "operationId" : "getRNList",
        "tags" : "RN list",
        "requestBody" : {
          "content" : {
            "application/json" : {
              "schema" : {
                "required" : [ ],
                "type" : "object",
                "properties" : {
                  "site_name" : {
                    "type" : "string",
                    "description" : "Name of the site",
                    "example" : "Remote-Conn1"
                  },
                  "edge_location_display_name" : {
                    "type" : "string",
                    "description" : "Name of PA location",
                    "example" : "US West"
                  },
                  "compute_location" : {
                    "type" : "string",
                    "description" : "Location of the compute",
                    "example" : "US East"
                  },
                  "site_state" : {
                    "type" : "number",
                    "description" : "State of the site",
                    "example" : 0
                  },
                  "instance_state" : {
                    "type" : "number",
                    "description" : "Instance state",
                    "example" : 1
                  },
                  "geoip_destination" : {
                    "type" : "string",
                    "description" : "Geo IP of the destination",
                    "example" : "Denver, United States"
                  }
                }
              },
              "examples" : {
                "Remote networks list with filters possible" : {
                  "value" : {
                    "filter" : {
                      "rules" : [ {
                        "property" : "event_time",
                        "operator" : "last_n_hours",
                        "values" : [ 5 ]
                      }, {
                        "property" : "site_state",
                        "operator" : "in",
                        "values" : [ 0 ]
                      }, {
                        "property" : "geoip_destination",
                        "operator" : "in",
                        "values" : [ "Denver, United States" ]
                      }, {
                        "property" : "edge_location_display_name",
                        "operator" : "in",
                        "values" : [ "US West" ]
                      }, {
                        "property" : "compute_location",
                        "operator" : "in",
                        "values" : [ "US East" ]
                      } ]
                    },
                    "properties" : [ {
                      "property" : "site_name"
                    }, {
                      "property" : "site_state_name"
                    }, {
                      "property" : "edge_location_display_name"
                    } ]
                  }
                },
                "Remote networks list" : {
                  "value" : {
                    "filter" : {
                      "rules" : [ {
                        "property" : "event_time",
                        "operator" : "last_n_hours",
                        "values" : [ 5 ]
                      } ]
                    },
                    "properties" : [ {
                      "property" : "site_name"
                    }, {
                      "property" : "site_state_name"
                    }, {
                      "property" : "edge_location_display_name"
                    } ]
                  }
                },
                "Monitor > Branch Sites > Site List" : {
                  "value" : {
                    "filter" : {
                      "rules" : [ {
                        "property" : "event_time",
                        "operator" : "last_n_hours",
                        "values" : [ 5 ]
                      } ]
                    },
                    "properties" : [ {
                      "property" : "site_name"
                    }, {
                      "property" : "site_state_name"
                    }, {
                      "property" : "edge_location_display_name"
                    } ]
                  }
                }
              }
            }
          },
          "required" : true
        },
        "responses" : {
          "200" : {
            "description" : "OK",
            "content" : {
              "application/json" : {
                "schema" : {
                  "type" : "object",
                  "properties" : {
                    "avg_throughput" : {
                      "type" : "number",
                      "description" : "Average throughput"
                    },
                    "site_type" : {
                      "type" : "string",
                      "description" : "site_type"
                    },
                    "bgp_site_state" : {
                      "type" : "integer",
                      "description" : "BGP Site State"
                    },
                    "site_disconnection" : {
                      "type" : "integer",
                      "description" : "Site Disconnection"
                    },
                    "site_state" : {
                      "type" : "integer",
                      "description" : "Site State"
                    },
                    "site_city" : {
                      "type" : "string",
                      "description" : "Site City"
                    },
                    "source_ip" : {
                      "type" : "string",
                      "description" : "Source IP"
                    },
                    "site_connection_duration" : {
                      "type" : "integer",
                      "description" : "Site Connection Duration"
                    },
                    "node_type" : {
                      "type" : "integer",
                      "description" : "Node Type"
                    },
                    "destination_ip" : {
                      "type" : "string",
                      "description" : "Destination IP"
                    },
                    "instance_state_name" : {
                      "type" : "string",
                      "description" : "Instance State Name"
                    },
                    "site_country" : {
                      "type" : "string",
                      "description" : "Site Country"
                    },
                    "instance_state" : {
                      "type" : "integer",
                      "description" : "Instance State"
                    },
                    "site_all_tunnels" : {
                      "type" : "integer",
                      "description" : "Count of tunnels"
                    },
                    "bgp_up_tunnels" : {
                      "type" : "integer",
                      "description" : "Count of Up Tunnels"
                    },
                    "bgp_site_state_name" : {
                      "type" : "string",
                      "description" : "BGP Site State Name"
                    },
                    "edge_location_display_name" : {
                      "type" : "string",
                      "description" : "PA Location"
                    },
                    "site_location_string" : {
                      "type" : "string",
                      "description" : "Site Location String"
                    },
                    "site_capacity" : {
                      "type" : "integer",
                      "description" : "Site Capacity"
                    },
                    "site_location" : {
                      "type" : "string",
                      "description" : "Site Location"
                    },
                    "destination_ip_string" : {
                      "type" : "string",
                      "description" : "Destination IP"
                    },
                    "median_throughput" : {
                      "type" : "number",
                      "description" : "Median throughput"
                    },
                    "source_ip_string" : {
                      "type" : "string",
                      "description" : "Source IP"
                    },
                    "site_name" : {
                      "type" : "string",
                      "description" : "site_name"
                    },
                    "compute_location" : {
                      "type" : "string",
                      "description" : "Compute Location"
                    },
                    "site_aggregate_capacity" : {
                      "type" : "integer",
                      "description" : "Site Aggregate Capacity"
                    },
                    "site_up_tunnels" : {
                      "type" : "integer",
                      "description" : "Count of Up Tunnels"
                    },
                    "site_state_name" : {
                      "type" : "string",
                      "description" : "Site State Name"
                    },
                    "bgp_all_tunnels" : {
                      "type" : "integer",
                      "description" : "Count of bgp tunnels"
                    },
                    "peak_throughput" : {
                      "type" : "number",
                      "description" : "Peak throughput"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/insights/v3.0/resource/query/sites/bandwidth_consumption_total" : {
      "post" : {
        "summary" : "Endpoint to get tunnel throughput",
        "operationId" : "getBandwidthConsumptionTotal",
        "tags" : "Bandwidth consumption total",
        "requestBody" : {
          "content" : {
            "application/json" : {
              "schema" : {
                "required" : [ "event_time" ],
                "type" : "object",
                "properties" : {
                  "event_time" : {
                    "type" : "string",
                    "description" : "Time of the event",
                    "example" : "1709226000000"
                  },
                  "edge_location_display_name" : {
                    "type" : "string",
                    "description" : "Name of PA location",
                    "example" : "US West"
                  },
                  "site_name" : {
                    "type" : "string",
                    "description" : "Name of the site",
                    "example" : "Remote-Conn1"
                  },
                  "node_type" : {
                    "type" : "number",
                    "description" : "Type of the node",
                    "example" : 48
                  },
                  "site_state" : {
                    "type" : "number",
                    "description" : "State of the site",
                    "example" : 0
                  },
                  "spn_name" : {
                    "type" : "string",
                    "description" : "SPN name",
                    "example" : "us-east-cedar"
                  },
                  "instance_state" : {
                    "type" : "number",
                    "description" : "Instance state",
                    "example" : 1
                  },
                  "compute_location" : {
                    "type" : "string",
                    "description" : "Location of the compute",
                    "example" : "US East"
                  }
                }
              },
              "examples" : {
                "Sample request will all filters" : {
                  "value" : {
                    "filter" : {
                      "rules" : [ {
                        "property" : "event_time",
                        "operator" : "last_n_hours",
                        "values" : [ 5 ]
                      }, {
                        "property" : "site_name",
                        "operator" : "in",
                        "values" : [ "Remote-Conn1" ]
                      }, {
                        "property" : "node_type",
                        "operator" : "in",
                        "values" : [ 48 ]
                      }, {
                        "property" : "edge_location_display_name",
                        "operator" : "in",
                        "values" : [ "US West" ]
                      }, {
                        "property" : "compute_location",
                        "operator" : "in",
                        "values" : [ "US East" ]
                      }, {
                        "property" : "site_state",
                        "operator" : "in",
                        "values" : [ 0 ]
                      } ]
                    }
                  }
                },
                "Bandwidth consumption" : {
                  "value" : {
                    "filter" : {
                      "rules" : [ {
                        "property" : "event_time",
                        "operator" : "last_n_hours",
                        "values" : [ 5 ]
                      }, {
                        "property" : "node_type",
                        "operator" : "in",
                        "values" : [ 48 ]
                      } ]
                    }
                  }
                }
              }
            }
          },
          "required" : true
        },
        "responses" : {
          "200" : {
            "description" : "OK",
            "content" : {
              "application/json" : {
                "schema" : {
                  "type" : "object",
                  "properties" : {
                    "p95_throughput" : {
                      "type" : "number",
                      "description" : "95th Percentile Tunnel Throughput"
                    },
                    "avg_throughput" : {
                      "type" : "number",
                      "description" : "Average Throughput"
                    },
                    "peak_throughput" : {
                      "type" : "number",
                      "description" : "Peak Throughput"
                    }
                  }
                }
              }
            }
          }
        }
      },
      "parameters" : [ {
        "name" : "Prisma-Tenant",
        "in" : "header",
        "description" : "TSG ID",
        "required" : false,
        "schema" : {
          "type" : "string"
        }
      } ]
    },
    "/insights/v3.0/resource/query/sites/sc_list" : {
      "post" : {
        "summary" : "Endpoint to get list of all sites list",
        "operationId" : "getSitesSCList",
        "tags" : "sites list",
        "requestBody" : {
          "content" : {
            "application/json" : {
              "schema" : {
                "required" : [ ],
                "type" : "object",
                "properties" : {
                  "site_name" : {
                    "type" : "string",
                    "description" : "Name of the site",
                    "example" : "Remote-Conn1"
                  },
                  "edge_location_display_name" : {
                    "type" : "string",
                    "description" : "Name of PA location",
                    "example" : "US West"
                  },
                  "site_state" : {
                    "type" : "number",
                    "description" : "State of the site",
                    "example" : 0
                  },
                  "instance_state" : {
                    "type" : "number",
                    "description" : "Instance state",
                    "example" : 1
                  }
                }
              },
              "example" : {
                "filter" : {
                  "rules" : [ {
                    "property" : "site_name",
                    "operator" : "in",
                    "values" : [ "Remote-Conn1" ]
                  }, {
                    "property" : "edge_location_display_name",
                    "operator" : "in",
                    "values" : [ "US West" ]
                  }, {
                    "property" : "site_state",
                    "operator" : "in",
                    "values" : [ 0 ]
                  }, {
                    "property" : "instance_state",
                    "operator" : "in",
                    "values" : [ 1 ]
                  } ]
                }
              }
            }
          },
          "required" : true
        },
        "responses" : {
          "200" : {
            "description" : "OK",
            "content" : {
              "application/json" : {
                "schema" : {
                  "type" : "object",
                  "properties" : {
                    "avg_throughput" : {
                      "type" : "number",
                      "description" : "Average throughput"
                    },
                    "site_type" : {
                      "type" : "string",
                      "description" : "Site Type"
                    },
                    "bgp_site_state" : {
                      "type" : "integer",
                      "description" : "BGP Site State"
                    },
                    "destination_ip_string" : {
                      "type" : "string",
                      "description" : "Destination IP"
                    },
                    "median_throughput" : {
                      "type" : "number",
                      "description" : "Median throughput"
                    },
                    "site_disconnection" : {
                      "type" : "integer",
                      "description" : "Site Disconnection"
                    },
                    "site_state" : {
                      "type" : "integer",
                      "description" : "Site State"
                    },
                    "source_ip_string" : {
                      "type" : "string",
                      "description" : "Source IP"
                    },
                    "source_ip" : {
                      "type" : "string",
                      "description" : "Source IP"
                    },
                    "site_name" : {
                      "type" : "string",
                      "description" : "Site Name"
                    },
                    "site_connection_duration" : {
                      "type" : "integer",
                      "description" : "Site Connection Duration"
                    },
                    "destination_ip" : {
                      "type" : "string",
                      "description" : "Destination IP"
                    },
                    "instance_state_name" : {
                      "type" : "string",
                      "description" : "Instance State Name"
                    },
                    "site_up_tunnels" : {
                      "type" : "integer",
                      "description" : "Count of Up Tunnels"
                    },
                    "instance_state" : {
                      "type" : "integer",
                      "description" : "Instance State"
                    },
                    "site_state_name" : {
                      "type" : "string",
                      "description" : "Site State Name"
                    },
                    "site_all_tunnels" : {
                      "type" : "integer",
                      "description" : "Count of tunnels"
                    },
                    "bgp_up_tunnels" : {
                      "type" : "integer",
                      "description" : "Count of Up Tunnels"
                    },
                    "bgp_site_state_name" : {
                      "type" : "string",
                      "description" : "BGP Site State Name"
                    },
                    "edge_location_display_name" : {
                      "type" : "string",
                      "description" : "PA Location"
                    },
                    "bgp_all_tunnels" : {
                      "type" : "integer",
                      "description" : "Count of bgp tunnels"
                    },
                    "peak_throughput" : {
                      "type" : "number",
                      "description" : "Peak throughput"
                    },
                    "site_capacity" : {
                      "type" : "integer",
                      "description" : "Site Capacity"
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  },
  "components" : {
    "securitySchemes" : {
      "JWT" : {
        "type" : "http",
        "description" : "JWT authentication with bearer token",
        "scheme" : "bearer",
        "bearerFormat" : "Bearer [token]"
      }
    }
  }
}